import dataclasses

__all__ = [
    "InitConfig",
    # HMM constructor
    "N_ITER_DEFAULT",
    "TOL_DEFAULT",
    "MIN_COVAR_DEFAULT",
    "STARTPROB_PRIOR_DEFAULT",
    "TRANSMAT_PRIOR_DEFAULT",
    "MEANS_PRIOR_DEFAULT",
    "MEANS_WEIGHT_DEFAULT",
    "COVARS_PRIOR_DEFAULT",
    "COVARS_WEIGHT_DEFAULT",
    # rdmst simulation
    "RDMST_N_SAMPLES_DEFAULT",
    "RDMST_DOF_DEFAULT",
]

# ── HMM constructor defaults ──────────────────────────────────────────────────
N_ITER_DEFAULT    = 20_000   # max EM iterations
TOL_DEFAULT       = 1e-7     # convergence tolerance on the EM lower bound
MIN_COVAR_DEFAULT = 1e-3     # diagonal floor added to covariances

STARTPROB_PRIOR_DEFAULT = 1.0   # Dirichlet prior: initial-state distribution
TRANSMAT_PRIOR_DEFAULT  = 1.0   # Dirichlet prior: each transition-matrix row
MEANS_PRIOR_DEFAULT     = 0     # Normal prior mean for emission means
MEANS_WEIGHT_DEFAULT    = 0     # Normal prior precision for emission means
COVARS_PRIOR_DEFAULT    = 1e-2  # Inverse-Wishart prior: covariance scale
COVARS_WEIGHT_DEFAULT   = 1     # Inverse-Wishart prior: degrees of freedom

# ── rdmst simulation defaults ─────────────────────────────────────────────────
RDMST_N_SAMPLES_DEFAULT = 5_000   # number of samples generated by rdmst
RDMST_DOF_DEFAULT       = 10      # degrees of freedom for rdmst


@dataclasses.dataclass
class InitConfig:
    """
    Tuning hyperparameters for the MsktHMM robust warm-start initialiser.

    All four values trade initialisation robustness against data with more
    frequent state changes. Reduce them when the diagonal of the fitted
    transition matrix is expected to be low (fast-switching regimes).

    Parameters
    ----------
    med_win : int, default=51
        Median-filter window applied to the first feature before 1D k-medians
        clustering seeds the initial state labels. Must be >= 3; even values
        are rounded up to the next odd automatically.
        Reduce for faster state transitions. Reasonable range: 3–501.

    min_seg : int, default=180
        Minimum dwell time (samples) enforced on each labelled segment after
        initial clustering. Short runs are merged into the adjacent longer
        segment. Must be >= 20; below this, segments are too short for a
        reliable skew-t fit.
        Reduce for faster state transitions.

    trim_q : float, default=0.98
        Quantile used to discard outliers before each per-state single-component
        skew-t fit. Observations whose MAD-normalised squared norm exceeds this
        quantile are removed, reducing the influence of boundary points
        mislabelled by the coarse clustering.
        Must be in [0.90, 0.999].

    n_frozen_iter : int, default=2
        Number of EM iterations immediately after initialisation in which
        emission parameters (means, covariances, skewness, dof) are frozen
        to the seed values. Only the discrete parameters (startprob, transmat)
        are updated during these iterations, letting the transition structure
        adapt before emission parameters are allowed to move. Must be >= 0.
        Increase for difficult initialisations; 0 disables freezing entirely.
    """
    med_win:       int   = 51
    min_seg:       int   = 180
    trim_q:        float = 0.98
    n_frozen_iter: int   = 2

    def __post_init__(self):
        if self.med_win < 3:
            raise ValueError(
                f"InitConfig.med_win must be >= 3, got {self.med_win}. "
                "Values below 3 leave too much noise in the seed labels."
            )
        if self.min_seg < 20:
            raise ValueError(
                f"InitConfig.min_seg must be >= 20, got {self.min_seg}. "
                "Shorter segments are too small for a reliable skew-t fit."
            )
        if not (0.90 <= self.trim_q <= 0.999):
            raise ValueError(
                f"InitConfig.trim_q must be in [0.90, 0.999], got {self.trim_q}. "
                "Outside this range outlier trimming destabilises the fit."
            )
        if self.n_frozen_iter < 0:
            raise ValueError(
                f"InitConfig.n_frozen_iter must be >= 0, got {self.n_frozen_iter}."
            )
